var name = "vinisha";
let age = 25;
const country = "India";
console.log("Name:", name);
console.log("Age:", age);
console.log("Country:", country);
name = "Sudevan";
age=26;
console.log("Updated Name:", name);
console.log("Updated Age:", age);
